# fly.toml app configuration file generated for da-course4 on 2023-07-24T15:20:17+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "da-course4"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
primary_region = "lax"

[build]
  image = "rcastanares/datingapp:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySetting__CloudName = "dkyov7phj"
  CloudinarySetting__ApiKey = "755561644943557"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[http_service]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

